### ISSUE TITLE
After Parsing Attach its not opening 

### ISSUE THREAD

**Issue by Zakriahassan44** [dickverweij/flutter_eml_parse#1]
I am a Flutter developer. I am creating the app in the app module First, we parsed the attachment, but it is not opening and also not fully downloading to the mobile storage, giving me the error Failed to load the file.
And they are not extracting the attachment and not showing me the data inside the attachment Please help with this problem. I am very thankful to you

**Comment by dickverweij** [comment]
Could you give a stack trace and possible the mail message?

**Comment by Zakriahassan44** [comment]
I/flutter (13453): Storage permission status: PermissionStatus.granted
I/flutter (13453): Directory already exists: /storage/emulated/0/Android/data/com.example.emlmsg_opner/files/Attachments
I/flutter (13453): File Path: /storage/emulated/0/Android/data/com.example.emlmsg_opner/files/Attachments/MehrozAltafHussian.pdf.pdf
I/flutter (13453): File exists: true
I/flutter (13453): File size: 148052 bytes
I/flutter (13453): File path: /storage/emulated/0/Android/data/com.example.emlmsg_opner/files/Attachments/MehrozAltafHussian.pdf.pdf
I/flutter (13453): Attachment written to file.
I/flutter (13453): File exists after writing: true
I/flutter (13453): File size after writing: 148052 bytes
I/flutter (13453): OpenFile result: ResultType.done, message: done
if i saved the attachment to the phone stoorage or open the attachment they give me error invaild formate and when we are cheak the file in file manager so they are corrupt  and not open  in app and filemanager


///////////////
Future<List<Attachment>> _parseAttachments(File file) async {
    try {
      print('Reading file as string...');
      String eml = await file.readAsString();
      print('File content: $eml');
      print('Parsing EML data...');

      EmlParseResult result = await parseEml(eml);
      print('Parsing result: ${result.attachments}');

      List<Attachment> attachments = [];
      try {
        if (result.attachments != null && result.attachments!.isNotEmpty) {
          for (EmlEmailAttachment attachment in result.attachments!) {
            if (attachment.data.isNotEmpty) {
              print('Attachment size: ${attachment.data.length} bytes');
              attachments.add(Attachment(
                name: attachment.name ?? 'Unknown Attachment',
                data: attachment.data,
              ));
              print('Attachment added: ${attachment.name}, size: ${attachment.data.length} bytes');

              // Print attachment data
              _printAttachmentData(Attachment(
                name: attachment.name ?? 'Unknown Attachment',
                data: attachment.data,
              ));
            } else {
              print('Attachment data is null for: ${attachment.name}');
            }
          }
        } else {
          print('No attachments found in the EML data.');
        }
      } catch (e) {
        print('Error processing attachments: $e');
      }

      return attachments;
    } catch (e) {
      print('Error reading or parsing the file: $e');
      return [];
    }
  }
  //////////////////////////////

**Comment by dickverweij** [comment]
I have added a test which reads a sample EML file with sample PDF file as attachment. 

run `flutter test` to test it. It will test if the PDF attachment is properly parsed.

![image](https://github.com/user-attachments/assets/0ad54a03-b73d-4bea-ab1a-27cd710b2f65)

@Zakriahassan44 you can swap the sample eml and sample pdf with your data to test if the parsing is correct

1) swap the files, rename them accordingly in the test (see `test/eml_parse_test.dart`)
2) run `flutter test`

**Comment by Zakriahassan44** [comment]
Thank you so much. It works
